#SPDX-License-Identifier: MIT-0
---
# tasks file for francescm.eza
- name: Instal gnupg and fontconfig packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - gnupg
    - fontconfig
- name: Install the gierens (eza) repo signing key into keyrings
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /etc/apt/keyrings/gierens.asc
    owner: root
    group: root
    mode: '0644'

- name: Add gierens APT repo (deb822)
  ansible.builtin.deb822_repository:
    name: gierens
    types: [deb]
    uris: ["http://deb.gierens.de"]
    suites: ["stable"]
    components: ["main"]
    signed_by: /etc/apt/keyrings/gierens.asc
    state: present
- name: Update repositories cache and install "eza"
  apt:
    name: eza
    update_cache: yes
- name: Creates font directory
  ansible.builtin.file:
    path: /usr/share/fonts/truetype/JetBrainsMonoNL
    state: directory
- name: Copy and expand the font ZIP file
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
    dest: /usr/share/fonts/truetype/JetBrainsMonoNL
    remote_src: yes
    creates: /usr/share/fonts/truetype/JetBrainsMonoNL/README.md
- name: Refresh font cache
  ansible.builtin.command: fc-cache -f -v
